### ISSUE TITLE
Create a style guide with HTML/CSS Snippets

### ISSUE THREAD

**Issue by melissamcewen** [FogCreek/shared-components#21]
High level goal would be to have a style guide that shows each component with:

- React code snippet (already there)
- HTML code snippet
- CSS code snippet

Why? It would make it easier to use components in non-React apps/projects. For example an app made by the partnership team that's just "plain" js/html. Or emails. 

In the past I've used systems like KSS for this but this was pre-React 
https://github.com/kss-node/kss-node

How? This may not be possible. [Phil from Styled-Components was skeptical of the usefulness/possibility](https://spectrum.chat/styled-components/general/export-styled-components-to-static-css-files~6b445df6-c807-472d-820b-f161bcacbd8e), but I'm curious to explore options. I notice the styles are available in a prop in the debugger but not sure how to access it within components. However, that prop isn't really CSS? 

Something like:
```
    <CodeExample>{`<Avatar variant="circle" src={user.avatarThumbnailUrl} defaultSrc={DEFAULT_USER_AVATAR} alt={user.name} />`}</CodeExample>
    <CodeExample>{HTML produced from React component}</CodeExample>
    <CodeExample>{CSS produced from styled}</CodeExample>
```

**Comment by modernserf** [comment]
This isn't really designed to be used outside of a React project; if we want to make shared styles available outside of React we should just write CSS instead of trying to extract them from styled components.

**Comment by melissamcewen** [comment]
Ah, then that would be a much larger scope than I thought, so I'll close this.
